name: maharashtra_board_books
description: Maharashtra Board Books flutter app

version: 1.0.0+1

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.4
  equatable: ^2.0.3
  http: ^0.13.4
  dartz: ^0.10.1
  cached_network_image: ^3.2.0
  path_provider: ^2.0.9
  flutter_animator: ^3.2.1
  lottie: ^1.2.2
  shared_preferences: any
  intl: ^0.17.0
  html: ^0.15.0
  url_launcher: ^6.0.20
  google_mobile_ads: ^1.1.0
  flutter_cached_pdfview: ^0.4.1
  share_plus: ^3.0.5
  device_info: ^2.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.4

flutter:

  uses-material-design: true

  assets:
    - assets/animations/lottiefiles/
    - assets/icons/
    - assets/icons/pngs/
    - assets/icons/svgs/
    - assets/images/
